### ISSUE TITLE
Any plan to support Mac OS?

### ISSUE THREAD

**Issue by pigLoveRabbit520** [rodrigocfd/windigo#12]
This repo is great! 
Any tiny gui library that supports mac os like this repo?

**Comment by rodrigocfd** [comment]
The gui package is built directly on top of the Win32 bindings, that's why it's tiny.

In order to have a gui package for MacOS you'd need native MacOS bindings first. It would be a completely different project. I know there are some packages around, but I don't really have any knowledge of them, because I don't have a Mac computer.

Anyway, there are a couple multi-platform gui libraries, which supposedly work for both Windows and MacOS, but they're way more complex because building a multi-platform gui is a very complex task.

**Comment by CarsonSlovoka** [comment]
I suggest looking in the direction of CEF(Chromium Embedded Framework), which can use web pages to present UI. There is webview2<sup>[example project](https://github.com/jchv/go-webview2), [another project](https://github.com/CarsonSlovoka/go-webview2/blob/526a1e9831bf603cc9b66b16dd27c7eb73b4e13e/examples/helloWorld/main.go#L78-L91)</sup> available on windows.

I think macOS will have a similar project in the future
